version: '3.8'

services:

  node:
    image: mosonyi/portainer-gitops-test:dev
    restart: always
    networks:
     - portainer-network
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        export TO_EMAIL=$(cat /run/configs/to_email_config)
        /entrypoint.sh
    environment:
     - NODENAME=node2
    configs:
      - source: to_email_config
        target: /run/configs/to_email_config
    deploy:
      replicas: 1

  smtp:
    image: juanluisbaptiste/postfix:latest
    restart: always
    networks:
     - portainer-network
    environment:
      - LOG_SUBJECT=true
    configs:
      - source: smtp_server_config
        target: /run/configs/smtp_server_config
      - source: smtp_user_config
        target: /run/configs/smtp_user_config
      - source: server_hostname_config
        target: /run/configs/server_hostname_config
      - source: smtp_password_secret
        target: /run/configs/smtp_password_secret
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        export SMTP_SERVER=$(cat /run/configs/smtp_server_config)
        export SMTP_USERNAME=$(cat /run/configs/smtp_user_config)
        export SMTP_PASSWORD=$(cat /run/configs/smtp_password_secret)
        export SERVER_HOSTNAME=$(cat /run/configs/server_hostname_config)
        exec postfix start

configs:
  to_email_config:
    external: 
      name: to_email_config
  smtp_server_config:
    external: 
      name: smtp_server_config
  smtp_user_config:
    external: 
      name: smtp_user_config
  server_hostname_config:
    external: 
      name: server_hostname_config
  smtp_password_secret:
    external: 
      name: smtp_password_secret

networks:
  portainer-network:
    driver: overlay