version: '3.7'

services:

  node:
    image: mosonyi/portainer-gitops-test:dev
    restart: always
    networks:
     - portainer-network
    environment:
     - TO_EMAIL=/run/secrets/to_email_config
     - NODENAME=node1
    configs:
      - source: to_email_config
        target: /run/secrets/to_email_config
    deploy:
      replicas: 1

  smtp:
    image: juanluisbaptiste/postfix:latest
    restart: always
    networks:
     - portainer-network
    environment:
      - SMTP_SERVER=/run/secrets/smtp_server_config
      - SMTP_USERNAME=/run/secrets/smtp_user_config
      - SERVER_HOSTNAME=/run/secrets/server_hostname_config
      - SMTP_PASSWORD=/run/secrets/smtp_password_secret
      - LOG_SUBJECT=true
    configs:
      - source: smtp_server_config
        target: /run/secrets/smtp_server_config
      - source: smtp_user_config
        target: /run/secrets/smtp_user_config
      - source: server_hostname_config
        target: /run/secrets/server_hostname_config
    secrets:
      - smtp_password_secret

configs:
  to_email_config:
    external: true
  smtp_server_config:
    external: true
  smtp_user_config:
    external: true
  server_hostname_config:
    external: true

networks:
  portainer-network:
    driver: overlay