version: '3.8'

services:

  node:
    image: mosonyi/portainer-gitops-test:dev
    restart: always
    networks:
      - portainer-network
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        export TO_EMAIL=$$(cat /run/configs/to_email_config)
        /entrypoint.sh
    environment:
      - NODENAME=node1
    configs:
      - source: to_email_config
        target: /run/configs/to_email_config
    deploy:
      replicas: 1

  smtp:
    image: juanluisbaptiste/postfix:latest
    restart: always
    networks:
      - portainer-network
    environment:
      - LOG_SUBJECT=true
    configs:
      - source: smtp_server_config
        target: /run/configs/smtp_server_config
      - source: smtp_user_config
        target: /run/configs/smtp_user_config
      - source: server_hostname_config
        target: /run/configs/server_hostname_config
      - source: smtp_password_secret
        target: /run/configs/smtp_password_secret
      - source: test_config
        target: /run/configs/test.conf
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        export SMTP_SERVER=$$(cat /run/configs/smtp_server_config)
        export SMTP_USERNAME=$$(cat /run/configs/smtp_user_config)
        export SMTP_PASSWORD=$$(cat /run/configs/smtp_password_secret)
        export SERVER_HOSTNAME=$$(cat /run/configs/server_hostname_config)
        exec /run.sh
configs:
  test_config:
    file: ./test.conf
  to_email_config:
    external: true
  smtp_server_config:
    external: true
  smtp_user_config:
    external: true
  server_hostname_config:
    external: true
  smtp_password_secret:
    external: true

networks:
  portainer-network:
    driver: overlay